"""Regenerate lib/covenant_consensus.py from the contract.

    python scripts/lift.py

The lifted module claims to be the agreement rules "as the contract runs them".
Maintaining it by hand makes that claim false the first time somebody edits one
side, and a copied rule that no deployed contract uses is worse than no copy at
all: it is a rule with a provenance it has not earned.

So the copy is generated, and tests/test_logic.py::TestLibParity compares the
two parsed trees function by function. Editing the contract and forgetting to
run this turns into a failing test rather than into a quiet lie.

scripts/mutate.py runs this inside every mutated copy before the suite, so the
parity test can never stand in for the behavioural test a mutation deserves.
"""

import ast
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "covenant.py"
OUT = ROOT / "lib" / "covenant_consensus.py"

CONSTANTS = [
    "MET", "BREACHED", "UNSTATED", "TOKENS",
    "KEPT", "BROKEN", "CURED", "UNREMEDIED", "TRANSITIONS",
    "COMPLIANT", "BREACH", "DEFAULT",
    "MAX_CONDITIONS", "MAX_CONDITION", "MAX_LABEL", "MAX_CURE", "MAX_REPORT",
    "MAX_REASON",
]

FUNCTIONS = [
    "looks_like_address", "clean_text", "split_conditions", "normalise_token",
    "parse_vector", "reconcile", "transition", "derive_transitions",
    "reachable", "parse_transitions", "structurally_sound", "covenant_agrees",
    "sanitise_reason", "fence", "build_prompt",
]

HEADER = '''# covenant_consensus.py - the agreement rules, lifted out to be copied.
#
# GENERATED by scripts/lift.py from contracts/covenant.py. Do not edit by hand:
# tests/test_logic.py compares the two parsed trees function by function, so an
# edit here fails the suite rather than quietly claiming a provenance it does
# not have.
#
# GenLayer contracts run as ONE Python file inside the GenVM. There is no pip
# install and no cross-file import at deploy time, so this is not a module you
# import into a contract: it is a curated block. contracts/covenant.py already
# inlines these helpers. This file exists so the rules can be read and lifted
# into another project without reading a whole contract first.
#
# Everything here is pure. No storage, no network, no model. These are the
# functions a validator runs to decide whether two nodes agreed, and a function
# that decides agreement must be deterministic or it decides nothing at all.
#
# covenant_agrees is SYMMETRIC: agrees(a, b, s) == agrees(b, a, s).
#
# The idea worth lifting is transition(). The model reads each condition as
# met, breached or unstated, but what crosses consensus is the transition that
# reading implies from the condition's current state, so two nodes compare
# exactly the distinctions that decide something and nothing else.

'''


def main():
    src = CONTRACT.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)

    def segment(node, with_comments=False):
        start = node.lineno - 1
        # A comment block sitting directly on top of a function is part of
        # what that function says, so it travels with it.
        while with_comments and start > 0 and lines[start - 1].startswith("#"):
            start -= 1
        return "".join(lines[start:node.end_lineno]).rstrip("\n")

    parts = []
    for name in CONSTANTS:
        for n in tree.body:
            if isinstance(n, ast.Assign) and any(
                    isinstance(t, ast.Name) and t.id == name for t in n.targets):
                parts.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}")

    fns = []
    for name in FUNCTIONS:
        for n in tree.body:
            if isinstance(n, ast.FunctionDef) and n.name == name:
                fns.append(segment(n, with_comments=True))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}()")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        HEADER + "\n".join(parts) + "\n\n\n" + "\n\n\n".join(fns) + "\n",
        encoding="utf-8", newline="\n",
    )
    print(f"  {OUT.relative_to(ROOT).as_posix()}: {len(CONSTANTS)} constants, "
          f"{len(FUNCTIONS)} functions")


if __name__ == "__main__":
    main()
